name: "Continuous Deployment to main"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VITE_FRONTEND_URL=${{ secrets.VITE_FRONTEND_URL }}
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}
            VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }}
            VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }}
            VITE_AUTH0_AUDIENCE=${{ secrets.VITE_AUTH0_AUDIENCE }}
            VITE_AUTH0_SCOPE=${{ secrets.VITE_AUTH0_SCOPE }}
            VITE_MANAGER_URL=${{ secrets.VITE_MANAGER_URL }}
            VITE_PERMISSIONS_URL=${{ secrets.VITE_PERMISSIONS_URL }}
          tags: |
            ghcr.io/ingsis-group-4/printscript-ui-main:${{ steps.short-sha.outputs.sha }}
            
      - name: Update server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_URL }}
          username: "snippet-searcher-admin"
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            cd snippet-infra
            docker compose -f docker-compose.prod.yml stop printscript-ui
            docker compose -f docker-compose.prod.yml pull printscript-ui
            docker compose -f docker-compose.prod.yml up printscript-ui -d --build
            
